create table if not exists profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  name text not null,
  email text not null,
  role text not null default 'user' check (role in ('user', 'admin')),
  created_at timestamp default now()
);

create table if not exists stores (
  id bigint generated by default as identity primary key,
  name text not null,
  address text not null,
  city text,
  latitude double precision,
  longitude double precision,
  google_maps_url text,
  opening_hours text,
  created_at timestamp default now()
);

create table if not exists categories (
  id bigint generated by default as identity primary key,
  name text not null,
  icon text,
  created_at timestamp default now()
);

create table if not exists promos (
  id bigint generated by default as identity primary key,
  store_id bigint references stores(id) on delete cascade,
  category_id bigint references categories(id) on delete set null,
  product_name text not null,
  brand text,
  image_url text,
  normal_price numeric not null,
  promo_price numeric not null,
  unit_size numeric,
  unit_type text,
  discount_percent numeric,
  start_date date not null,
  end_date date not null,
  terms text,
  source_url text,
  is_active boolean default true,
  created_at timestamp default now()
);

create table if not exists favorites (
  id bigint generated by default as identity primary key,
  user_id uuid references profiles(id) on delete cascade,
  promo_id bigint references promos(id) on delete cascade,
  created_at timestamp default now(),
  unique(user_id, promo_id)
);

create table if not exists reminders (
  id bigint generated by default as identity primary key,
  user_id uuid references profiles(id) on delete cascade,
  promo_id bigint references promos(id) on delete cascade,
  reminder_time timestamp not null,
  is_notified boolean default false,
  created_at timestamp default now(),
  unique(user_id, promo_id)
);

create table if not exists shopping_lists (
  id bigint generated by default as identity primary key,
  user_id uuid references profiles(id) on delete cascade,
  promo_id bigint references promos(id) on delete cascade,
  quantity int default 1,
  note text,
  is_purchased boolean default false,
  created_at timestamp default now(),
  unique(user_id, promo_id)
);

create table if not exists price_comparisons (
  id bigint generated by default as identity primary key,
  user_id uuid references profiles(id) on delete cascade,
  product_a_name text not null,
  product_a_price numeric not null,
  product_a_size numeric not null,
  product_a_unit text not null,
  product_b_name text not null,
  product_b_price numeric not null,
  product_b_size numeric not null,
  product_b_unit text not null,
  product_a_unit_price numeric,
  product_b_unit_price numeric,
  cheaper_product text,
  created_at timestamp default now()
);

